---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.2

before_install:
 - gem install rubygems-update -v '<3' && update_rubygems
 - gem install bundler -v 2.2.8

notifications:
  slack: fadendaten:tWoet2mtObvbwSZSyUAY93jl
  email: false
